version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  mysql_data:
